### ISSUE TITLE
ZanyBonzy - Malicious users can DOS onERC1155Received by donating fcash before the contract is deployed.

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-12-notional-update-5-judging#3]
ZanyBonzy

medium

# Malicious users can DOS onERC1155Received by donating fcash before the contract is deployed.

## Summary
A malicious actor through deduction or frontrunning can get the address of the contract and send existing fCash to it before deployment and since nothing has been deployed, onERC1155Received will not be called and the address will accept the fCash. 
## Vulnerability Detail
The wfCash contract checks whether the contract only owns one fcash and reverts if there's more than one fcash positions. A malicious user would cause the `onERC1155Received` revert if he donates some fcash before the contract is deployed either by predicting the CREATE2 address or frontrunning. 
## Impact
Users will no longer be able to deposit `wrappedFcash` through transferring `fcash` to the contract as the attacker can make function `onERC1155Received()` to revert all the time.
## Code Snippet
https://github.com/sherlock-audit/2023-12-notional-update-5/blob/3bf2fb5d992dfd5aa7343d7788e881d3a4294b13/wrapped-fcash/contracts/wfCashLogic.sol#L157
## Tool used
Manual Code Review

## Recommendation
Recommend removing the check.

**Comment by jeffywu** [comment]
This was reported in the previous Wrapped fCash audit and a method was added here to resolve the issue:
https://github.com/notional-finance/wrapped-fcash/blob/feat/support-notional-v3/contracts/wfCashLogic.sol#L198-L215
